spring:
  application:
    name: addService
server:
  port: 8222

eureka:
  port: 8111
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/
