server:
  port: 8001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/plokij74/spring-cloud
          search-paths: config-repo #git相对路径
          username: plokij74
          password: wzw123456
eureka:
  port: 8111
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/