spring:
  application:
    name: fegin-consumer
server:
  port: 8555
feign:
  hystrix:
    enabled: true #开启hystrix支持
eureka:
  instance:
    hostname: localhost
    port: 8111
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  server:
    servlet:
      context-path: / #spring-boot2.0以上需要加这个参数，不知道为什么