spring:
  application:
    name: fegin-consumer
server:
  port: 8555
eureka:
  instance:
    hostname: localhost
    port: 8111
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/